version: "3.9"

services:
    nginx:
        container_name: nginx-messaging-system
        image: nginx:latest
        ports:
            - "8903:80"
        volumes:
            - ..:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
        restart: always
        networks:
            - app-network

    phpfpm:
        container_name: phpfpm-messaging-system
        build: ./php/
        working_dir: /var/www
        restart: always
        volumes:
            - ..:/var/www
        networks:
            - app-network

    mysql:
        container_name: mysql-messaging-system
        build:
            context: .
            dockerfile: mysql/Dockerfile
        working_dir: /app
        restart: always
        volumes:
            - .data/mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=messaging_system
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - "3200:3306"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
